### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pablo-develop** [pablo-develop/clojuremacs#1]
- [x] cljr keybindings
- [ ] pretty print keybinding (, p & ,P)
- [ ] inline keybindings (, E & , F)
- [ ] control-c as esc
- [ ] f5 cider test report
- [ ] remove traces minor mode
- [ ] fix file path in modeline
- [ ] collapse comment blocks
- [ ] https://docs.cider.mx/cider/testing/running_tests.html#display-test-report-on-success
